#!/usr/bin/env python3
"""
Generate a development Ed25519 signing key for bOPEN context access tokens.

Work package: BOPEN-P35-001 (WP-P35-03)
Governing artifact: BOPEN-IDP-001 section 12.4
Registry entry: CRED-TOKEN-CONTEXT-SIGNING in docs/07-security/secrets/BOPEN-SEC-VAULT-001.md

Development keys only. Section 12.4 requires production signing keys to be managed outside
source control by an external secret manager, and a key generated by a repository tool is not
that. The output is printed to stdout and written nowhere: this tool cannot create the file that
someone later commits by accident.

Usage:
    python tools/generate_token_key.py            # print an .env.local line
    python tools/generate_token_key.py --jwks     # also print the public JWKS entry

Then paste the BOPEN_CONTEXT_TOKEN_KEY line into .env.local, which .gitignore excludes.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services" / "platform-kernel" / "python"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--jwks", action="store_true", help="also print the public JWKS entry"
    )
    args = parser.parse_args()

    try:
        from platform_kernel import tokens
    except ImportError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    private_pem, public_pem, kid = tokens.generate_keypair()

    # Environment variables cannot portably carry literal newlines, so the PEM is escaped.
    escaped = private_pem.replace("\n", "\\n")

    print("# bOPEN context token signing key (development only)")
    print("# Registry: CRED-TOKEN-CONTEXT-SIGNING — BOPEN-SEC-VAULT-001")
    print(f"# Key ID (RFC 7638 thumbprint): {kid}")
    print("#")
    print("# Paste the following line into .env.local, which .gitignore excludes.")
    print("# Never commit it, and never paste it into an agent conversation — name the")
    print("# variable instead. An agent needs the variable name, not the value.")
    print()
    print(f'BOPEN_CONTEXT_TOKEN_KEY="{escaped}"')

    if args.jwks:
        print()
        print("# Public key — safe to publish. Served at /.well-known/jwks.json")
        print("#")
        for line in public_pem.strip().splitlines():
            print(f"# {line}")
        registry = tokens.KeyRegistry()
        registry.add_verification_key(public_pem)
        print("#")
        for line in json.dumps(registry.jwks(), indent=2).splitlines():
            print(f"# {line}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
